/**
 * Registers all bundled FILLED icon variants under `<name>-fill` keys.
 *
 * Generated by `scripts/fill-icons.js` — do not edit by hand.
 *
 *   import "@waggylabs/yumekit/icons/all-filled.js";
 *   <y-icon name="heart" weight="filled"></y-icon>
 */

import { registerIcons } from "./registry.js";

import accessibilityFill from "./filled/accessibility.svg";
import archiveFill from "./filled/archive.svg";
import arrowDownFill from "./filled/arrow-down.svg";
import arrowLeftFill from "./filled/arrow-left.svg";
import arrowRightFill from "./filled/arrow-right.svg";
import arrowUpFill from "./filled/arrow-up.svg";
import bellFill from "./filled/bell.svg";
import bluetoothFill from "./filled/bluetooth.svg";
import boltFill from "./filled/bolt.svg";
import bookmarkFill from "./filled/bookmark.svg";
import briefcaseFill from "./filled/briefcase.svg";
import bugFill from "./filled/bug.svg";
import calendarFill from "./filled/calendar.svg";
import campfireFill from "./filled/campfire.svg";
import checkFill from "./filled/check.svg";
import chevronDownFill from "./filled/chevron-down.svg";
import chevronLeftFill from "./filled/chevron-left.svg";
import chevronRightFill from "./filled/chevron-right.svg";
import chevronUpFill from "./filled/chevron-up.svg";
import circleExclamationFill from "./filled/circle-exclamation.svg";
import circleInfoFill from "./filled/circle-info.svg";
import circleQuestionFill from "./filled/circle-question.svg";
import circleSlashFill from "./filled/circle-slash.svg";
import clipboardFill from "./filled/clipboard.svg";
import clockFill from "./filled/clock.svg";
import cloudFill from "./filled/cloud.svg";
import codeFill from "./filled/code.svg";
import compassFill from "./filled/compass.svg";
import copyFill from "./filled/copy.svg";
import discordFill from "./filled/discord.svg";
import downFromBracketFill from "./filled/down-from-bracket.svg";
import downToBracketFill from "./filled/down-to-bracket.svg";
import ellipsisHFill from "./filled/ellipsis-h.svg";
import ellipsisVFill from "./filled/ellipsis-v.svg";
import evChargerFill from "./filled/ev-charger.svg";
import expandDownFill from "./filled/expand-down.svg";
import expandLeftFill from "./filled/expand-left.svg";
import expandRightFill from "./filled/expand-right.svg";
import expandUpFill from "./filled/expand-up.svg";
import faceFrownFill from "./filled/face-frown.svg";
import faceNeutralFill from "./filled/face-neutral.svg";
import faceSmileFill from "./filled/face-smile.svg";
import fanFill from "./filled/fan.svg";
import fastBackFill from "./filled/fast-back.svg";
import fastForwardFill from "./filled/fast-forward.svg";
import figmaFill from "./filled/figma.svg";
import flaskFill from "./filled/flask.svg";
import floppyDiskFill from "./filled/floppy-disk.svg";
import flowerFill from "./filled/flower.svg";
import folderFill from "./filled/folder.svg";
import funnelFill from "./filled/funnel.svg";
import gasolineFill from "./filled/gasoline.svg";
import gearFill from "./filled/gear.svg";
import githubFill from "./filled/github.svg";
import globeFill from "./filled/globe.svg";
import gridFill from "./filled/grid.svg";
import heartFill from "./filled/heart.svg";
import homeFill from "./filled/home.svg";
import iconFill from "./filled/icon.svg";
import imageFill from "./filled/image.svg";
import leftFromBracketFill from "./filled/left-from-bracket.svg";
import leftToBracketFill from "./filled/left-to-bracket.svg";
import linkFill from "./filled/link.svg";
import listBulletFill from "./filled/list-bullet.svg";
import listCheckFill from "./filled/list-check.svg";
import lockFill from "./filled/lock.svg";
import magnifyingGlassFill from "./filled/magnifying-glass.svg";
import mailFill from "./filled/mail.svg";
import mapMarkerFill from "./filled/map-marker.svg";
import menuFill from "./filled/menu.svg";
import minusFill from "./filled/minus.svg";
import monitorFill from "./filled/monitor.svg";
import moonFill from "./filled/moon.svg";
import paletteFill from "./filled/palette.svg";
import paperAirplaneFill from "./filled/paper-airplane.svg";
import pauseFill from "./filled/pause.svg";
import pencilFill from "./filled/pencil.svg";
import playFill from "./filled/play.svg";
import plugFill from "./filled/plug.svg";
import plusFill from "./filled/plus.svg";
import puzzleFill from "./filled/puzzle.svg";
import redoFill from "./filled/redo.svg";
import rightFromBracketFill from "./filled/right-from-bracket.svg";
import rightToBracketFill from "./filled/right-to-bracket.svg";
import robotFill from "./filled/robot.svg";
import scissorsFill from "./filled/scissors.svg";
import shareFill from "./filled/share.svg";
import shieldFill from "./filled/shield.svg";
import skipBackFill from "./filled/skip-back.svg";
import skipForwardFill from "./filled/skip-forward.svg";
import smartphoneFill from "./filled/smartphone.svg";
import speechBubbleFill from "./filled/speech-bubble.svg";
import stackFill from "./filled/stack.svg";
import starFill from "./filled/star.svg";
import stopFill from "./filled/stop.svg";
import sunFill from "./filled/sun.svg";
import swapFill from "./filled/swap.svg";
import tabletFill from "./filled/tablet.svg";
import tagFill from "./filled/tag.svg";
import thermometerHighFill from "./filled/thermometer-high.svg";
import thermometerLowFill from "./filled/thermometer-low.svg";
import thumbsDownFill from "./filled/thumbs-down.svg";
import thumbsUpFill from "./filled/thumbs-up.svg";
import thumbtackFill from "./filled/thumbtack.svg";
import tooltipFill from "./filled/tooltip.svg";
import trashFill from "./filled/trash.svg";
import triangleExclamationFill from "./filled/triangle-exclamation.svg";
import undoFill from "./filled/undo.svg";
import unlockFill from "./filled/unlock.svg";
import upFromBracketFill from "./filled/up-from-bracket.svg";
import upToBracketFill from "./filled/up-to-bracket.svg";
import userFill from "./filled/user.svg";
import usersFill from "./filled/users.svg";
import waveformFill from "./filled/waveform.svg";
import wrenchFill from "./filled/wrench.svg";
import xFill from "./filled/x.svg";

registerIcons({
    "accessibility-fill": accessibilityFill,
    "archive-fill": archiveFill,
    "arrow-down-fill": arrowDownFill,
    "arrow-left-fill": arrowLeftFill,
    "arrow-right-fill": arrowRightFill,
    "arrow-up-fill": arrowUpFill,
    "bell-fill": bellFill,
    "bluetooth-fill": bluetoothFill,
    "bolt-fill": boltFill,
    "bookmark-fill": bookmarkFill,
    "briefcase-fill": briefcaseFill,
    "bug-fill": bugFill,
    "calendar-fill": calendarFill,
    "campfire-fill": campfireFill,
    "check-fill": checkFill,
    "chevron-down-fill": chevronDownFill,
    "chevron-left-fill": chevronLeftFill,
    "chevron-right-fill": chevronRightFill,
    "chevron-up-fill": chevronUpFill,
    "circle-exclamation-fill": circleExclamationFill,
    "circle-info-fill": circleInfoFill,
    "circle-question-fill": circleQuestionFill,
    "circle-slash-fill": circleSlashFill,
    "clipboard-fill": clipboardFill,
    "clock-fill": clockFill,
    "cloud-fill": cloudFill,
    "code-fill": codeFill,
    "compass-fill": compassFill,
    "copy-fill": copyFill,
    "discord-fill": discordFill,
    "down-from-bracket-fill": downFromBracketFill,
    "down-to-bracket-fill": downToBracketFill,
    "ellipsis-h-fill": ellipsisHFill,
    "ellipsis-v-fill": ellipsisVFill,
    "ev-charger-fill": evChargerFill,
    "expand-down-fill": expandDownFill,
    "expand-left-fill": expandLeftFill,
    "expand-right-fill": expandRightFill,
    "expand-up-fill": expandUpFill,
    "face-frown-fill": faceFrownFill,
    "face-neutral-fill": faceNeutralFill,
    "face-smile-fill": faceSmileFill,
    "fan-fill": fanFill,
    "fast-back-fill": fastBackFill,
    "fast-forward-fill": fastForwardFill,
    "figma-fill": figmaFill,
    "flask-fill": flaskFill,
    "floppy-disk-fill": floppyDiskFill,
    "flower-fill": flowerFill,
    "folder-fill": folderFill,
    "funnel-fill": funnelFill,
    "gasoline-fill": gasolineFill,
    "gear-fill": gearFill,
    "github-fill": githubFill,
    "globe-fill": globeFill,
    "grid-fill": gridFill,
    "heart-fill": heartFill,
    "home-fill": homeFill,
    "icon-fill": iconFill,
    "image-fill": imageFill,
    "left-from-bracket-fill": leftFromBracketFill,
    "left-to-bracket-fill": leftToBracketFill,
    "link-fill": linkFill,
    "list-bullet-fill": listBulletFill,
    "list-check-fill": listCheckFill,
    "lock-fill": lockFill,
    "magnifying-glass-fill": magnifyingGlassFill,
    "mail-fill": mailFill,
    "map-marker-fill": mapMarkerFill,
    "menu-fill": menuFill,
    "minus-fill": minusFill,
    "monitor-fill": monitorFill,
    "moon-fill": moonFill,
    "palette-fill": paletteFill,
    "paper-airplane-fill": paperAirplaneFill,
    "pause-fill": pauseFill,
    "pencil-fill": pencilFill,
    "play-fill": playFill,
    "plug-fill": plugFill,
    "plus-fill": plusFill,
    "puzzle-fill": puzzleFill,
    "redo-fill": redoFill,
    "right-from-bracket-fill": rightFromBracketFill,
    "right-to-bracket-fill": rightToBracketFill,
    "robot-fill": robotFill,
    "scissors-fill": scissorsFill,
    "share-fill": shareFill,
    "shield-fill": shieldFill,
    "skip-back-fill": skipBackFill,
    "skip-forward-fill": skipForwardFill,
    "smartphone-fill": smartphoneFill,
    "speech-bubble-fill": speechBubbleFill,
    "stack-fill": stackFill,
    "star-fill": starFill,
    "stop-fill": stopFill,
    "sun-fill": sunFill,
    "swap-fill": swapFill,
    "tablet-fill": tabletFill,
    "tag-fill": tagFill,
    "thermometer-high-fill": thermometerHighFill,
    "thermometer-low-fill": thermometerLowFill,
    "thumbs-down-fill": thumbsDownFill,
    "thumbs-up-fill": thumbsUpFill,
    "thumbtack-fill": thumbtackFill,
    "tooltip-fill": tooltipFill,
    "trash-fill": trashFill,
    "triangle-exclamation-fill": triangleExclamationFill,
    "undo-fill": undoFill,
    "unlock-fill": unlockFill,
    "up-from-bracket-fill": upFromBracketFill,
    "up-to-bracket-fill": upToBracketFill,
    "user-fill": userFill,
    "users-fill": usersFill,
    "waveform-fill": waveformFill,
    "wrench-fill": wrenchFill,
    "x-fill": xFill,
});
