name: Publish

on:
    release:
        types: [published]
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    test:
        uses: ./.github/workflows/ci.yml

    publish-beta:
        if: github.event.release.prerelease == true
        needs: test
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/npm-publish.yml
        with:
            tag: beta
        secrets: inherit

    publish-release:
        if: github.event_name == 'workflow_dispatch' || github.event.release.prerelease == false
        needs: test
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/npm-publish.yml
        secrets: inherit

    deploy-storybook:
        if: github.event_name == 'workflow_dispatch' || github.event.release.prerelease == false
        needs: test
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-storybook.yml
        secrets: inherit
